### ISSUE TITLE
Smart voucher reservation feature

### ISSUE THREAD

**Issue by starkmsu** [OpenMAVN/MAVN.Service.SmartVouchers#5]
1) Expose endpoints for smart voucher reservation and reservation cancellation
a) for voucher reservation - replace BuyVoucherAsync with ReserveVoucherAsync
b) for voucher reservation cancellation - add CancelVoucherReservationAsync(string shortCode)

2) Implement exposed endpoints

Implementation details:
Preserve existing buy voucher logic - it would be used in #6

**Comment by ofmaska** [comment]
++

**Comment by starkmsu** [comment]
Updated service is deployed to internal environment
